# Pacotes

In [1]:
import pandas as pd
import numpy as np

# Funcoes

Funcoes originarias de : 

    Model for SPATIAL and data cleaning
    
    https://github.com/IBM/spatial-lstm/blob/a18fb9fda2d9c8e5311cf1f46e3173f82a21ad24/Model/model.py#L163

In [2]:
########################
###### Normalizador ####
########################


def normalizador_min_max(dados, variaveis):
    
    for j in variaveis:
        menor = min(dados[str(j)]) 
        maior = max(dados[str(j)])
        
        dif = maior - menor
        if dif==0:
            dif=1 
        
        for i in range(dados.shape[0]):
            dados.loc[i,j] = (dados[str(j)][i]-menor)/ dif

    return(dados) 


def normalizador_log(dados, variaveis):
    
    for j in variaveis:
        for i in range(dados.shape[0]):
            if dados[str(j)][i] > 0 :
                dados.loc[i,str(j)] = np.log(dados[str(j)][i])
            else:
                dados.loc[i,str(j)] = 1e-5

    return(dados)

# Importacao dos dados

In [5]:
df = pd.read_csv('df_limpo.csv').drop(columns=['Unnamed: 0'])

In [6]:
df

,n_coord,id_estacao,ocorrencia,lon_ocr,lat_ocr,id_tempo_x,tempo,vintequatrohoras,Altitude_numerica,Declividade_numerica,...,flg_comunidades,flg_agricola,flg_exploracao_mineral,flg_rocha,flg_cobertura_vegetal,flg_afloramento_rochoso,flg_favela,flg_ocupacao_desordenada,flg_areas_de_risco,graurisc
0,0,522,0,-43.086620,-22.988275,11648701,2019-02-24 09:00:00.000,24.0,69.984214,40.678449,...,0,0,0,0,1,0,0,0,0,0
1,1,520,0,-43.082962,-22.987606,11648701,2019-02-24 09:00:00.000,24.2,36.737055,37.835880,...,0,0,0,0,1,0,0,0,0,0
2,2,520,0,-43.084463,-22.987003,11648701,2019-02-24 09:00:00.000,24.2,74.609010,29.264552,...,0,0,0,0,1,0,0,0,0,0
3,3,520,0,-43.082218,-22.986478,11648701,2019-02-24 09:00:00.000,24.2,29.972561,25.306148,...,0,0,0,0,1,0,0,0,0,0
4,4,509,0,-43.067935,-22.985091,11648701,2019-02-24 09:00:00.000,24.0,33.783319,34.557911,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496255,3130,526,0,-43.060272,-22.900743,13756861,2023-02-27 09:00:00.000,24.0,144.456732,35.188423,...,0,0,0,0,1,0,0,0,0,0
4496256,3131,524,0,-43.051521,-22.880147,13756861,2023-02-27 09:00:00.000,24.0,117.953718,21.597753,...,1,0,0,0,0,0,1,0,1,3
4496257,3132,508,0,-43.071238,-22.905491,13756861,2023-02-27 09:00:00.000,24.0,112.470204,18.078663,...,1,0,0,0,0,0,1,0,0,0
4496258,3133,515,0,-43.078925,-22.889827,13756861,2023-02-27 09:00:00.000,24.0,88.340525,34.796558,...,1,0,0,0,0,0,1,0,1,2
4496259,3134,516,0,-43.075202,-22.873257,13756861,2023-02-27 09:00:00.000,24.0,54.729613,18.974280,...,1,0,0,0,0,0,0,0,0,0

Transformação logarítimica para variáveis com distribuição assimétrica e variáveis com muitos zeros.

In [7]:
normalizador_log(df, ["vintequatrohoras", "Altitude_numerica", "Declividade_numerica", "graurisc"])

,n_coord,id_estacao,ocorrencia,lon_ocr,lat_ocr,id_tempo_x,tempo,vintequatrohoras,Altitude_numerica,Declividade_numerica,...,flg_comunidades,flg_agricola,flg_exploracao_mineral,flg_rocha,flg_cobertura_vegetal,flg_afloramento_rochoso,flg_favela,flg_ocupacao_desordenada,flg_areas_de_risco,graurisc
0,0,522,0,-43.086620,-22.988275,11648701,2019-02-24 09:00:00.000,3.178054,4.248270,3.705698,...,0,0,0,0,1,0,0,0,0,0.000010
1,1,520,0,-43.082962,-22.987606,11648701,2019-02-24 09:00:00.000,3.186353,3.603786,3.633258,...,0,0,0,0,1,0,0,0,0,0.000010
2,2,520,0,-43.084463,-22.987003,11648701,2019-02-24 09:00:00.000,3.186353,4.312261,3.376377,...,0,0,0,0,1,0,0,0,0,0.000010
3,3,520,0,-43.082218,-22.986478,11648701,2019-02-24 09:00:00.000,3.186353,3.400282,3.231047,...,0,0,0,0,1,0,0,0,0,0.000010
4,4,509,0,-43.067935,-22.985091,11648701,2019-02-24 09:00:00.000,3.178054,3.519967,3.542636,...,0,0,0,0,1,0,0,0,0,0.000010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496255,3130,526,0,-43.060272,-22.900743,13756861,2023-02-27 09:00:00.000,3.178054,4.972980,3.560717,...,0,0,0,0,1,0,0,0,0,0.000010
4496256,3131,524,0,-43.051521,-22.880147,13756861,2023-02-27 09:00:00.000,3.178054,4.770292,3.072589,...,1,0,0,0,0,0,1,0,1,1.098612
4496257,3132,508,0,-43.071238,-22.905491,13756861,2023-02-27 09:00:00.000,3.178054,4.722688,2.894732,...,1,0,0,0,0,0,1,0,0,0.000010
4496258,3133,515,0,-43.078925,-22.889827,13756861,2023-02-27 09:00:00.000,3.178054,4.481199,3.549518,...,1,0,0,0,0,0,1,0,1,0.693147
4496259,3134,516,0,-43.075202,-22.873257,13756861,2023-02-27 09:00:00.000,3.178054,4.002405,2.943084,...,1,0,0,0,0,0,0,0,0,0.000010

Transformação min-max para variáveis com distribuições semelhantes da normal.

In [8]:
normalizador_min_max(df, ['lon_ocr', 'lat_ocr', 'Orientacao_numerica', 'Curv_Vertical_numerica', 'Curv_Horizontal_numerica', 'Relevo_sombreado_numerico'])

,n_coord,id_estacao,ocorrencia,lon_ocr,lat_ocr,id_tempo_x,tempo,vintequatrohoras,Altitude_numerica,Declividade_numerica,...,flg_comunidades,flg_agricola,flg_exploracao_mineral,flg_rocha,flg_cobertura_vegetal,flg_afloramento_rochoso,flg_favela,flg_ocupacao_desordenada,flg_areas_de_risco,graurisc
0,0,522,0,0.258607,0.000000,11648701,2019-02-24 09:00:00.000,3.178054,4.248270,3.705698,...,0,0,0,0,1,0,0,0,0,0.000010
1,1,520,0,0.279000,0.005332,11648701,2019-02-24 09:00:00.000,3.186353,3.603786,3.633258,...,0,0,0,0,1,0,0,0,0,0.000010
2,2,520,0,0.270631,0.010137,11648701,2019-02-24 09:00:00.000,3.186353,4.312261,3.376377,...,0,0,0,0,1,0,0,0,0,0.000010
3,3,520,0,0.283148,0.014324,11648701,2019-02-24 09:00:00.000,3.186353,3.400282,3.231047,...,0,0,0,0,1,0,0,0,0,0.000010
4,4,509,0,0.362788,0.025383,11648701,2019-02-24 09:00:00.000,3.178054,3.519967,3.542636,...,0,0,0,0,1,0,0,0,0,0.000010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496255,3130,526,0,0.405514,0.697788,13756861,2023-02-27 09:00:00.000,3.178054,4.972980,3.560717,...,0,0,0,0,1,0,0,0,0,0.000010
4496256,3131,524,0,0.454307,0.861975,13756861,2023-02-27 09:00:00.000,3.178054,4.770292,3.072589,...,1,0,0,0,0,0,1,0,1,1.098612
4496257,3132,508,0,0.344369,0.659939,13756861,2023-02-27 09:00:00.000,3.178054,4.722688,2.894732,...,1,0,0,0,0,0,1,0,0,0.000010
4496258,3133,515,0,0.301508,0.784811,13756861,2023-02-27 09:00:00.000,3.178054,4.481199,3.549518,...,1,0,0,0,0,0,1,0,1,0.693147
4496259,3134,516,0,0.322268,0.916904,13756861,2023-02-27 09:00:00.000,3.178054,4.002405,2.943084,...,1,0,0,0,0,0,0,0,0,0.000010

In [9]:
#df.hist(bins=30, figsize=(30,30))

In [10]:
df = df.interpolate(method ='linear')

In [11]:
df.to_csv('df_norm.csv')

In [12]:
df

,n_coord,id_estacao,ocorrencia,lon_ocr,lat_ocr,id_tempo_x,tempo,vintequatrohoras,Altitude_numerica,Declividade_numerica,...,flg_comunidades,flg_agricola,flg_exploracao_mineral,flg_rocha,flg_cobertura_vegetal,flg_afloramento_rochoso,flg_favela,flg_ocupacao_desordenada,flg_areas_de_risco,graurisc
0,0,522,0,0.258607,0.000000,11648701,2019-02-24 09:00:00.000,3.178054,4.248270,3.705698,...,0,0,0,0,1,0,0,0,0,0.000010
1,1,520,0,0.279000,0.005332,11648701,2019-02-24 09:00:00.000,3.186353,3.603786,3.633258,...,0,0,0,0,1,0,0,0,0,0.000010
2,2,520,0,0.270631,0.010137,11648701,2019-02-24 09:00:00.000,3.186353,4.312261,3.376377,...,0,0,0,0,1,0,0,0,0,0.000010
3,3,520,0,0.283148,0.014324,11648701,2019-02-24 09:00:00.000,3.186353,3.400282,3.231047,...,0,0,0,0,1,0,0,0,0,0.000010
4,4,509,0,0.362788,0.025383,11648701,2019-02-24 09:00:00.000,3.178054,3.519967,3.542636,...,0,0,0,0,1,0,0,0,0,0.000010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496255,3130,526,0,0.405514,0.697788,13756861,2023-02-27 09:00:00.000,3.178054,4.972980,3.560717,...,0,0,0,0,1,0,0,0,0,0.000010
4496256,3131,524,0,0.454307,0.861975,13756861,2023-02-27 09:00:00.000,3.178054,4.770292,3.072589,...,1,0,0,0,0,0,1,0,1,1.098612
4496257,3132,508,0,0.344369,0.659939,13756861,2023-02-27 09:00:00.000,3.178054,4.722688,2.894732,...,1,0,0,0,0,0,1,0,0,0.000010
4496258,3133,515,0,0.301508,0.784811,13756861,2023-02-27 09:00:00.000,3.178054,4.481199,3.549518,...,1,0,0,0,0,0,1,0,1,0.693147
4496259,3134,516,0,0.322268,0.916904,13756861,2023-02-27 09:00:00.000,3.178054,4.002405,2.943084,...,1,0,0,0,0,0,0,0,0,0.000010