In [1]:
!pip install joypy
import pandas as pd
from joypy import joyplot
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
#! pip install plotly
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#sns.set_theme(style="white", context="talk")

Requirement already satisfied: joypy in ./env/lib/python3.8/site-packages (0.2.6)
Requirement already satisfied: numpy>=1.16.5 in ./env/lib/python3.8/site-packages (from joypy) (1.24.1)
Requirement already satisfied: matplotlib in ./env/lib/python3.8/site-packages (from joypy) (3.6.2)
Requirement already satisfied: scipy>=0.11.0 in ./env/lib/python3.8/site-packages (from joypy) (1.10.0)
Requirement already satisfied: pandas>=0.20.0 in ./env/lib/python3.8/site-packages (from joypy) (1.5.2)
Requirement already satisfied: pyparsing>=2.2.1 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (9.4.0)
Requirement already satisfied: contourpy>=1.0.1 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (1.0.6)
Requirement already satisfied: packaging>=20.0 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (22.0)
Requirement already satisfied: fonttools>=4.22.0 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (4.38.0)
Requirement already satisfied: python-dateutil>=2.7 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (1.4.4)
Requirement already satisfied: cycler>=0.10 in ./env/lib/python3.8/site-packages (from matplotlib->joypy) (0.11.0)
Requirement already satisfied: pytz>=2020.1 in ./env/lib/python3.8/site-packages (from pandas>=0.20.0->joypy) (2022.7)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->joypy) (1.16.0)

In [2]:
df = pd.read_csv('df_final_4.csv')

In [3]:
df['vintequatrohoras'].max()

34030.4

In [4]:
data  = pd.read_csv('dim_tempo_202305212244.csv')

In [5]:
# Realizar o merge dos DataFrames com base nas colunas "id_tempo_x" e "id_tempo"
df = pd.merge(df, data[['id_tempo', 'tempo']], left_on='id_tempo_x', right_on='id_tempo', how='left')

# Preencher os valores nulos na coluna "tempo_x" com os valores correspondentes
df['tempo_x'].fillna(df['tempo_y'], inplace=True)

# Remover colunas desnecessárias após o preenchimento
df.drop(['id_tempo', 'tempo_y'], axis=1, inplace=True)

In [6]:
df

,n_coord,id_estacao,ocorrencia,lon_ocr,lat_ocr,id_tempo_x,tempo_x,vintequatrohoras,Altitude_numerica,Declividade_numerica,...,flg_comunidades,flg_agricola,flg_exploracao_mineral,flg_rocha,flg_cobertura_vegetal,flg_afloramento_rochoso,flg_favela,flg_ocupacao_desordenada,flg_areas_de_risco,graurisc
0,1773,500,0.0,-43.109831,-22.898302,13756861,2023-02-27 09:00:00.000,0.0,35.619689,28.211760,...,0,0,0,0,0,0,0,0,0,0
1,1805,500,0.0,-43.108610,-22.897677,13756861,2023-02-27 09:00:00.000,0.0,46.275318,33.994978,...,0,0,0,0,0,0,0,0,0,0
2,1843,500,0.0,-43.110489,-22.896457,13756861,2023-02-27 09:00:00.000,0.0,40.805991,21.622332,...,0,0,0,0,0,0,0,0,0,0
3,1844,500,0.0,-43.107389,-22.896594,13756861,2023-02-27 09:00:00.000,0.0,34.978839,33.074273,...,0,0,0,0,0,0,0,0,0,0
4,1909,500,0.0,-43.109172,-22.894250,13756861,2023-02-27 09:00:00.000,0.0,30.671250,26.927709,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4185883,3070,501,1.0,-43.109845,-22.867703,13681981,2023-01-06 09:00:00.000,NaN,21.471093,27.421508,...,1,0,0,0,0,0,1,0,0,0
4185884,3080,501,1.0,-43.100091,-22.868319,13726621,2023-02-06 09:00:00.000,NaN,36.725784,33.086335,...,1,0,0,0,0,0,0,0,0,0
4185885,3121,501,1.0,-43.095614,-22.868662,12599101,2020-12-15 09:00:00.000,NaN,18.138746,21.584124,...,1,0,0,0,0,0,0,0,0,0
4185886,3122,501,1.0,-43.099089,-22.868207,12597661,2020-12-14 09:00:00.000,NaN,50.494469,33.332941,...,0,0,0,0,0,0,0,0,0,0
4185887,2780,509,1.0,-43.043500,-22.971115,11713501,2019-04-10 09:00:00.000,79.8,39.008540,30.304515,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df.rename(columns={'tempo_x': 'tempo'}, inplace=True)

# Verificar as ocorrências por estação no tempo de estudo

In [10]:
df_ocorr = df.groupby(['id_estacao', 'yyyy-mm']).agg({'ocorrencia': 'sum', 'vintequatrohoras': ['min', 'mean', 'max']}).reset_index()

In [14]:
df.groupby(['id_estacao']).agg({'ocorrencia': 'sum', 'n_coord': 'nunique'}).reset_index()

    id_estacao  ocorrencia  n_coord
0          500         9.0       23
1          501        30.0       37
2          502        42.0       73
3          503        58.0       85
4          504        78.0      113
5          505        19.0       31
6          506        96.0       87
7          507         5.0      263
8          508        74.0      101
9          509         1.0      119
10         510        12.0       60
11         511        42.0       99
12         512        19.0      220
13         513        13.0      233
14         514        10.0       25
15         515        50.0      111
16         516        27.0       58
17         517        12.0       39
18         518         2.0       12
19         519         6.0       31
20         520         2.0       47
21         521        28.0      161
22         522        14.0      133
23         523         4.0      168
24         524        46.0      110
25         525         6.0       50
26         526        69.0      234
27         527        28.0       43
28         528        66.0      101
29         529         6.0      268

In [11]:
df_ocorr

     id_estacao  yyyy-mm ocorrencia vintequatrohoras
                                sum              min       mean    max
0           500  2019-02        0.0              0.0   8.059259   75.0
1           500  2019-03        0.0              0.0   7.070968   93.4
2           500  2019-04        1.0              0.0  10.047170  109.4
3           500  2019-05        0.0              0.0   3.381818   25.0
4           500  2019-06        0.0              0.0   2.166667   30.0
...         ...      ...        ...              ...        ...    ...
1434        529  2022-10        0.0              0.0   1.458065   10.2
1435        529  2022-11        0.0              0.0   8.506667  106.8
1436        529  2022-12        0.0              0.0   4.655172   26.6
1437        529  2023-01        0.0              0.0   6.193548   95.6
1438        529  2023-02        1.0              0.0   8.867958  119.0

[1439 rows x 6 columns]

In [12]:
df_ocorr.to_csv('df_analise.csv')

# Avaliar a completude dos dados em cada estação ao longo do tempo

In [9]:
df['yyyy-mm'] = pd.to_datetime(df['tempo']).dt.strftime('%Y-%m')

In [16]:
df_tempo = df[['id_estacao','yyyy-mm','tempo']].drop_duplicates()

In [17]:
df_dias = df_tempo.groupby(['id_estacao','yyyy-mm'])['tempo'].count().reset_index(name='Qtd_dias')

In [18]:
pd.set_option('display.max_rows', None)

In [19]:
df_dias

      id_estacao  yyyy-mm  Qtd_dias
0            500  2019-02        27
1            500  2019-03        31
2            500  2019-04        24
3            500  2019-05        22
4            500  2019-06        30
5            500  2019-07        31
6            500  2019-08        31
7            500  2019-09        30
8            500  2019-11        30
9            500  2019-12        31
10           500  2020-01        31
11           500  2020-02        29
12           500  2020-03        31
13           500  2020-04        30
14           500  2020-05        31
15           500  2020-06        30
16           500  2020-07        31
17           500  2020-08        31
18           500  2020-09        30
19           500  2020-10        31
20           500  2020-11        30
21           500  2020-12         2
22           500  2021-01        31
23           500  2021-02        28
24           500  2021-03        31
25           500  2021-04        30
26           500  2021-05        31
27           500  2021-06        30
28           500  2021-07        29
29           500  2021-08        30
30           500  2021-09        28
31           500  2021-10        31
32           500  2021-11        19
33           500  2021-12         1
34           500  2022-01        30
35           500  2022-02        28
36           500  2022-03        31
37           500  2022-04        30
38           500  2022-05        31
39           500  2022-06        30
40           500  2022-07        31
41           500  2022-08        31
42           500  2022-09        30
43           500  2022-10        31
44           500  2022-11        30
45           500  2022-12        31
46           500  2023-01        31
47           500  2023-02        27
48           501  2019-02        27
49           501  2019-03        31
50           501  2019-04        30
51           501  2019-05        28
52           501  2019-06        30
53           501  2019-07        29
54           501  2019-08        31
55           501  2019-09        30
56           501  2019-10        31
57           501  2019-11        28
58           501  2019-12        31
59           501  2020-01        31
60           501  2020-02        26
61           501  2020-03        31
62           501  2020-04        28
63           501  2020-05        31
64           501  2020-06        20
65           501  2020-07        27
66           501  2020-08        28
67           501  2020-09        28
68           501  2020-10        31
69           501  2020-11        30
70           501  2020-12         8
71           501  2021-01        30
72           501  2021-02        28
73           501  2021-03        31
74           501  2021-04        30
75           501  2021-05        30
76           501  2021-06        30
77           501  2021-07        31
78           501  2021-08        31
79           501  2021-09        30
80           501  2021-10        31
81           501  2021-11        19
82           501  2021-12         1
83           501  2022-01        31
84           501  2022-02        28
85           501  2022-03        31
86           501  2022-04        30
87           501  2022-05        31
88           501  2022-06        30
89           501  2022-07        31
90           501  2022-08        31
91           501  2022-09        30
92           501  2022-10        31
93           501  2022-11        30
94           501  2022-12        31
95           501  2023-01         2
96           501  2023-02         2
97           502  2019-02        27
98           502  2019-03        31
99           502  2019-04        30
100          502  2019-05        31
101          502  2019-06        28
102          502  2019-07        31
103          502  2019-08        31
104          502  2019-09        30
105          502  2019-10        31
106          502  2019-11        30
107          502  2019-12        31
108          502  2020-01        31
109          502  2020-02        29
110          502  2020-03        31
111          502  2020-04        30
112          502  2020-05        31
113          502  2020-07        31
114          502  2020-08        31
115          502  2020-09        30
116          502  2020-10        31
117          502  2020-11        30
118          502  2020-12         5
119          502  2021-01        29
120          502  2021-02        28
121          502  2021-03        31
122          502  2021-04        30
123          502  2021-05        31
124          502  2021-06        29
125          502  2021-07        31
126          502  2021-08        31
127          502  2021-09        30
128          502  2021-10        31
129          502  2021-11        19
130          502  2021-12         1
131          502  2022-01        31
132          502  2022-02        28
133          502  2022-03        31
134          502  2022-04        30
135          502  2022-05        31
136          502  2022-06        30
137          502  2022-07        31
138          502  2022-08        31
139          502  2022-09        30
140          502  2022-10        31
141          502  2022-11        30
142          502  2022-12        31
143          502  2023-01        31
144          502  2023-02        27
145          503  2019-02        22
146          503  2019-03        17
147          503  2019-04        30
148          503  2019-05        25
149          503  2019-06        26
150          503  2019-07        23
151          503  2019-08        25
152          503  2019-09        16
153          503  2019-10        17
154          503  2019-11        30
155          503  2019-12        31
156          503  2020-01        31
157          503  2020-02        29
158          503  2020-03        31
159          503  2020-04        30
160          503  2020-05        31
161          503  2020-06        30
162          503  2020-07        24
163          503  2020-08        27
164          503  2020-09        30
165          503  2020-10        27
166          503  2020-11        30
167          503  2020-12         3
168          503  2021-01        31
169          503  2021-02        28
170          503  2021-03        31
171          503  2021-04        30
172          503  2021-05        29
173          503  2021-06        30
174          503  2021-07        31
175          503  2021-08        31
176          503  2021-09        30
177          503  2021-10        29
178          503  2021-11        19
179          503  2021-12         2
180          503  2022-01        31
181          503  2022-02        28
182          503  2022-03        31
183          503  2022-04        30
184          503  2022-05        31
185          503  2022-06        30
186          503  2022-07        31
187          503  2022-08        31
188          503  2022-09        30
189          503  2022-10        31
190          503  2022-11        30
191          503  2022-12        31
192          503  2023-01         3
193          503  2023-02         7
194          504  2019-02        27
195          504  2019-03        31
196          504  2019-04        30
197          504  2019-05        31
198          504  2019-06        30
199          504  2019-07        31
200          504  2019-08        31
201          504  2019-09        30
202          504  2019-10        31
203          504  2019-11        30
204          504  2019-12        31
205          504  2020-01        31
206          504  2020-02        29
207          504  2020-03        31
208          504  2020-04        30
209          504  2020-05        31
210          504  2020-06        30
211          504  2020-07        17
212          504  2020-08        31
213          504  2020-09        30
214          504  2020-10        31
215          504  2020-11        30
216          504  2020-12         2
217          504  2021-01        31
218          504  2021-02        28
219          504  2021-03        31
220          504  2021-04        30
221          504  2021-05        31
222          504  2021-06        30
223          504  2021-07        31
224          504  2021-08        31
225          504  2021-09        30
226          504  2021-10        31
227          504  2021-11        19
228          504  2021-12         1
229          504  2022-01        31
230          504  2022-02        28
231          504  2022-03        31
232          504  2022-04        30
233          504  2022-05        31
234          504  2022-06        30
235          504  2022-07        31
236          504  2022-08        31
237          504  2022-09        30
238          504  2022-10        31
239          504  2022-11        30
240          504  2022-12        31
241          504  2023-01        31
242          504  2023-02        27
243          505  2019-02        27
244          505  2019-03        31
245          505  2019-04        30
246          505  2019-05        31
247          505  2019-06        30
248          505  2019-07        31
249          505  2019-08        31
250          505  2019-09        30
251          505  2019-10        31
252          505  2019-11        30
253          505  2019-12        31
254          505  2020-01        31
255          505  2020-02        29
256          505  2020-03        31
257          505  2020-04        30
258          505  2020-05        31
259          505  2020-06        30
260          505  2020-07        31
261          505  2020-08        29
262          505  2020-09        30
263          505  2020-10        29
264          505  2020-11        29
265          505  2020-12         1
266          505  2021-01        31
267          505  2021-02        28
268          505  2021-03        31
269          505  2021-04        29
270          505  2021-05        30
271          505  2021-06        30
272          505  2021-07        31
273          505  2021-08        31
274          505  2021-09        30
275          505  2021-10        31
276          505  2021-11        19
277          505  2021-12         1
278          505  2022-01        31
279          505  2022-02        28
280          505  2022-03        31
281          505  2022-04        30
282          505  2022-05        31
283          505  2022-06        30
284          505  2022-07        31
285          505  2022-08        31
286          505  2022-09        30
287          505  2022-10        31
288          505  2022-11        30
289          505  2022-12        31
290          505  2023-01        31
291          505  2023-02        27
292          506  2019-02        25
293          506  2019-03        30
294          506  2019-04        29
295          506  2019-05        24
296          506  2019-06        30
297          506  2019-07        10
298          506  2019-08        24
299          506  2019-09        12
300          506  2019-10        16
301          506  2019-11        23
302          506  2019-12        31
303          506  2020-01        31
304          506  2020-02        29
305          506  2020-03        31
306          506  2020-04        30
307          506  2020-05        31
308          506  2020-06        30
309          506  2020-07        29
310          506  2020-08        29
311          506  2020-09        30
312          506  2020-10        31
313          506  2020-11        30
314          506  2020-12         8
315          506  2021-01        31
316          506  2021-02        28
317          506  2021-03        31
318          506  2021-04        30
319          506  2021-05        31
320          506  2021-06        30
321          506  2021-07        31
322          506  2021-08        31
323          506  2021-09        30
324          506  2021-10        31
325          506  2021-11        19
326          506  2021-12         1
327          506  2022-01        31
328          506  2022-02        28
329          506  2022-03        31
330          506  2022-04        30
331          506  2022-05        31
332          506  2022-06        30
333          506  2022-07        29
334          506  2022-08        31
335          506  2022-09        30
336          506  2022-10        29
337          506  2022-11        30
338          506  2022-12        29
339          506  2023-01        31
340          506  2023-02        27
341          507  2019-02        27
342          507  2019-03        31
343          507  2019-04        30
344          507  2019-05        31
345          507  2019-06        30
346          507  2019-07        29
347          507  2019-08        31
348          507  2019-09        30
349          507  2019-10        31
350          507  2019-11        30
351          507  2019-12        31
352          507  2020-01        31
353          507  2020-02        29
354          507  2020-03        31
355          507  2020-04        30
356          507  2020-05        31
357          507  2020-06        30
358          507  2020-07        31
359          507  2020-08        31
360          507  2020-09        30
361          507  2020-10        31
362          507  2020-11        28
363          507  2021-01        31
364          507  2021-02        28
365          507  2021-03        31
366          507  2021-04        30
367          507  2021-05        30
368          507  2021-06        29
369          507  2021-07        31
370          507  2021-08        31
371          507  2021-09        30
372          507  2021-10        31
373          507  2021-11        19
374          507  2021-12         1
375          507  2022-01        31
376          507  2022-02        28
377          507  2022-03        31
378          507  2022-04        30
379          507  2022-05        31
380          507  2022-06        30
381          507  2022-07        31
382          507  2022-08        31
383          507  2022-09        30
384          507  2022-10        30
385          507  2022-11        29
386          507  2022-12        31
387          507  2023-01        31
388          507  2023-02        27
389          508  2019-02        24
390          508  2019-03        31
391          508  2019-04        30
392          508  2019-05        25
393          508  2019-06        30
394          508  2019-07        25
395          508  2019-08        25
396          508  2019-09        28
397          508  2019-10        31
398          508  2019-11        30
399          508  2019-12         1
400          508  2020-01        31
401          508  2020-02        29
402          508  2020-03        31
403          508  2020-04        30
404          508  2020-05        31
405          508  2020-06        30
406          508  2020-07        31
407          508  2020-08        31
408          508  2020-09        30
409          508  2020-10        31
410          508  2020-11        30
411          508  2020-12         6
412          508  2021-01        31
413          508  2021-02        28
414          508  2021-03        31
415          508  2021-04        30
416          508  2021-05        31
417          508  2021-06        30
418          508  2021-07        31
419          508  2021-08        31
420          508  2021-09        30
421          508  2021-10        31
422          508  2021-11        19
423          508  2021-12         2
424          508  2022-01        31
425          508  2022-02        28
426          508  2022-03        31
427          508  2022-04        30
428          508  2022-05        31
429          508  2022-06        30
430          508  2022-07        31
431          508  2022-08        31
432          508  2022-09        30
433          508  2022-10        29
434          508  2022-11        30
435          508  2022-12        31
436          508  2023-01        31
437          508  2023-02        27
438          509  2019-02        27
439          509  2019-03        31
440          509  2019-04        30
441          509  2019-05        31
442          509  2019-06        30
443          509  2019-07        31
444          509  2019-08        31
445          509  2019-09        30
446          509  2019-10        31
447          509  2019-11        30
448          509  2019-12        31
449          509  2020-01        31
450          509  2020-02        29
451          509  2020-03        31
452          509  2020-04        30
453          509  2020-05        31
454          509  2020-06        30
455          509  2020-07        31
456          509  2020-08        31
457          509  2020-09        30
458          509  2020-10        31
459          509  2020-11        30
460          509  2021-01        31
461          509  2021-02        28
462          509  2021-03        31
463          509  2021-04        30
464          509  2021-05        31
465          509  2021-06        30
466          509  2021-07        31
467          509  2021-08        31
468          509  2021-09        30
469          509  2021-10        31
470          509  2021-11        19
471          509  2021-12         1
472          510  2019-02        27
473          510  2019-03        31
474          510  2019-04        30
475          510  2019-05        31
476          510  2019-06        30
477          510  2019-07        31
478          510  2019-08        31
479          510  2019-09        30
480          510  2019-10        31
481          510  2019-11        30
482          510  2019-12        31
483          510  2020-01        31
484          510  2020-02        29
485          510  2020-03        31
486          510  2020-04        30
487          510  2020-05        31
488          510  2020-06        30
489          510  2020-07        31
490          510  2020-08        31
491          510  2020-09        30
492          510  2020-10        31
493          510  2020-11        30
494          510  2021-01        31
495          510  2021-02        28
496          510  2021-03        31
497          510  2021-04        30
498          510  2021-05        31
499          510  2021-06        30
500          510  2021-07        31
501          510  2021-08        31
502          510  2021-09        30
503          510  2021-10        31
504          510  2021-11        19
505          510  2021-12         1
506          510  2022-01        31
507          510  2022-02        28
508          510  2022-03        31
509          510  2022-04        30
510          510  2022-05        31
511          510  2022-06        30
512          510  2022-07        31
513          510  2022-08        31
514          510  2022-09        30
515          510  2022-10        31
516          510  2022-11        30
517          510  2022-12        31
518          510  2023-01        30
519          510  2023-02        26
520          511  2019-02        27
521          511  2019-03        31
522          511  2019-04        30
523          511  2019-05        31
524          511  2019-06        30
525          511  2019-07        31
526          511  2019-08        31
527          511  2019-09        30
528          511  2019-10        31
529          511  2019-11        30
530          511  2019-12        31
531          511  2020-01        31
532          511  2020-02        26
533          511  2020-03        31
534          511  2020-04        30
535          511  2020-05        31
536          511  2020-06        30
537          511  2020-07        31
538          511  2020-08        31
539          511  2020-09        30
540          511  2020-10        31
541          511  2020-11        30
542          511  2020-12         4
543          511  2021-01        31
544          511  2021-02        28
545          511  2021-03        31
546          511  2021-04        30
547          511  2021-05        31
548          511  2021-06        30
549          511  2021-07        31
550          511  2021-08        29
551          511  2021-09        30
552          511  2021-10        29
553          511  2021-11        17

In [9]:
lista = [501, 508, 515, 500, 516, 524, 528, 522, 517, 506, 503, 529]

import plotly.express as px
for i in lista:
    print('-'*20)
    print(i)

    usar = df_dias.loc[df_dias['id_estacao'] == i]

    fig = px.bar(usar, x='yyyy-mm', y='Qtd_dias', title='Estação '+str(i),labels={
                     "yyyy-mm": "Data",
                     "Qtd_dias": "Quantidade de dias preenchidos",
                 })
    fig.show()

# Retirar estações ruins

In [10]:
estacoes_ruins = lista
df = df[~df['id_estacao'].isin(estacoes_ruins)]

In [18]:
df.to_csv('df_limpo.csv')

In [20]:
df_dias.to_csv('df_teste.csv')

In [21]:
df